package codegen

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/Homiakus/axiom/internal/compiler"
	"github.com/Homiakus/axiom/internal/lang"
)

type Options struct {
	PackageName string
	SourcePath  string
	Source      []byte
	Format      string
}

type File struct {
	Name    string
	Content []byte
	Once    bool
}

func Generate(module *compiler.Module, opts Options) ([]File, error) {
	if module == nil {
		return nil, fmt.Errorf("module is required")
	}
	if opts.PackageName == "" {
		return nil, fmt.Errorf("package name is required")
	}
	domain := exportName(module.Domain)
	if domain == "" {
		return nil, fmt.Errorf("module domain is required")
	}
	base := lowerSnake(module.Domain)
	if base == "" {
		base = "axiom"
	}
	gen, err := generatedFile(module, opts, domain)
	if err != nil {
		return nil, err
	}
	stubs, err := stubsFile(module, opts, domain)
	if err != nil {
		return nil, err
	}
	return []File{
		{Name: base + "_axiom.gen.go", Content: gen},
		{Name: base + "_activities.go", Content: stubs, Once: true},
	}, nil
}

func generatedFile(module *compiler.Module, opts Options, domain string) ([]byte, error) {
	var b bytes.Buffer
	hash := sha256.Sum256(opts.Source)
	activities := externalActivities(module)
	comments := newCommentIndex(opts.Source)
	fmt.Fprintf(&b, "// Code generated by axiomgen from %s; DO NOT EDIT.\n\n", filepath.ToSlash(opts.SourcePath))
	fmt.Fprintf(&b, "package %s\n\n", opts.PackageName)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, "\t\"context\"")
	fmt.Fprintln(&b, "\t\"fmt\"")
	fmt.Fprintln(&b, "")
	fmt.Fprintln(&b, "\t\"github.com/Homiakus/axiom\"")
	if strings.EqualFold(opts.Format, "toml") {
		fmt.Fprintln(&b, "\t\"github.com/Homiakus/axiom/table\"")
	}
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "const %sAXMHash = %q\n\n", domain, fmt.Sprintf("%x", hash[:]))
	fmt.Fprintf(&b, "const %sAXMSource = %q\n\n", domain, string(opts.Source))
	writeActivityNameConsts(&b, activities, comments)
	writeTypes(&b, module, activities, comments)
	writeInterface(&b, domain, activities, comments)
	writeLoadAndNew(&b, domain, activities, opts)
	writeAdapters(&b, module, activities)
	writeHelpers(&b)
	return format.Source(b.Bytes())
}

type commentIndex map[int][]string

func newCommentIndex(source []byte) commentIndex {
	text := strings.ReplaceAll(string(source), "\r\n", "\n")
	index := commentIndex{}
	var pending []string
	for i, line := range strings.Split(text, "\n") {
		lineNo := i + 1
		code, comment, hasComment := splitAXMComment(line)
		if strings.TrimSpace(code) == "" {
			if hasComment {
				pending = append(pending, comment)
			}
			continue
		}
		if len(pending) > 0 {
			index[lineNo] = append(index[lineNo], pending...)
			pending = nil
		}
		if hasComment {
			index[lineNo] = append(index[lineNo], comment)
		}
	}
	return index
}

func splitAXMComment(line string) (string, string, bool) {
	inString := false
	escaped := false
	for i, r := range line {
		if escaped {
			escaped = false
			continue
		}
		if r == '\\' {
			escaped = true
			continue
		}
		if r == '"' {
			inString = !inString
			continue
		}
		if r == '#' && !inString {
			return line[:i], cleanAXMComment(line[i:]), true
		}
	}
	return line, "", false
}

func cleanAXMComment(comment string) string {
	comment = strings.TrimSpace(comment)
	comment = strings.TrimPrefix(comment, "#")
	return strings.TrimSpace(comment)
}

func writeLineComments(b *bytes.Buffer, comments commentIndex, line int, indent string) {
	for _, comment := range comments[line] {
		if comment == "" {
			continue
		}
		fmt.Fprintf(b, "%s// %s\n", indent, comment)
	}
}

func stubsFile(module *compiler.Module, opts Options, domain string) ([]byte, error) {
	var b bytes.Buffer
	activities := externalActivities(module)
	comments := newCommentIndex(opts.Source)
	fmt.Fprintf(&b, "package %s\n\n", opts.PackageName)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, "\t\"context\"")
	fmt.Fprintln(&b, "\t\"fmt\"")
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "type %sActivityImpl struct{}\n\n", domain)
	if len(activities) == 0 {
		fmt.Fprintf(&b, "// %sActivityImpl has no external activities to implement.\n", domain)
	}
	for _, activity := range activities {
		name := exportName(activity.Name)
		writeLineComments(&b, comments, activity.Line, "")
		fmt.Fprintf(&b, "func (%sActivityImpl) %s(ctx context.Context, input %sInput) (%sOutput, error) {\n", domain, name, name, name)
		fmt.Fprintf(&b, "\treturn %sOutput{}, fmt.Errorf(\"%s is not implemented\")\n", name, activity.Name)
		fmt.Fprintln(&b, "}")
		fmt.Fprintln(&b)
	}
	return format.Source(b.Bytes())
}

func writeActivityNameConsts(b *bytes.Buffer, activities []lang.ActivityDecl, comments commentIndex) {
	if len(activities) == 0 {
		return
	}
	fmt.Fprintln(b, "const (")
	for _, activity := range activities {
		writeLineComments(b, comments, activity.Line, "\t")
		fmt.Fprintf(b, "\tActivity%s = %q\n", exportName(activity.Name), activity.Name)
	}
	fmt.Fprintln(b, ")")
	fmt.Fprintln(b)
}

func writeTypes(b *bytes.Buffer, module *compiler.Module, activities []lang.ActivityDecl, comments commentIndex) {
	for _, activity := range activities {
		name := exportName(activity.Name)
		writeLineComments(b, comments, activity.Line, "")
		fmt.Fprintf(b, "type %sInput struct {\n", name)
		for _, input := range activity.Input {
			field := exportName(input.Name)
			writeLineComments(b, comments, input.Line, "\t")
			fmt.Fprintf(b, "\t%s %s `json:%q`\n", field, goType(inferBindingType(module, input)), input.Name)
		}
		fmt.Fprintln(b, "}")
		fmt.Fprintln(b)
		writeLineComments(b, comments, activity.Line, "")
		fmt.Fprintf(b, "type %sOutput struct {\n", name)
		for _, output := range activity.Output {
			field := exportName(output.Name)
			writeLineComments(b, comments, output.Line, "\t")
			fmt.Fprintf(b, "\t%s %s `json:%q`\n", field, goType(output.Type), output.Name)
		}
		fmt.Fprintln(b, "}")
		fmt.Fprintln(b)
	}
}

func writeInterface(b *bytes.Buffer, domain string, activities []lang.ActivityDecl, comments commentIndex) {
	fmt.Fprintf(b, "type %sActivities interface {\n", domain)
	for _, activity := range activities {
		name := exportName(activity.Name)
		writeLineComments(b, comments, activity.Line, "\t")
		fmt.Fprintf(b, "\t%s(ctx context.Context, input %sInput) (%sOutput, error)\n", name, name, name)
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeLoadAndNew(b *bytes.Buffer, domain string, activities []lang.ActivityDecl, opts Options) {
	path := opts.SourcePath
	if path == "" {
		path = domain + ".axm"
	}
	fmt.Fprintf(b, "func Load%s() (*axiom.App, error) {\n", domain)
	if strings.EqualFold(opts.Format, "toml") {
		fmt.Fprintf(b, "\tplan, err := table.Parse([]byte(%sAXMSource))\n", domain)
		fmt.Fprintln(b, "\tif err != nil {")
		fmt.Fprintln(b, "\t\treturn nil, err")
		fmt.Fprintln(b, "\t}")
		fmt.Fprintf(b, "\treturn &axiom.App{Path: %q, Module: plan.Module()}, nil\n", filepath.ToSlash(path))
	} else {
		fmt.Fprintf(b, "\tmodule, err := axiom.CompileAny([]byte(%sAXMSource), axiom.WithSourceName(%q))\n", domain, filepath.ToSlash(path))
		fmt.Fprintln(b, "\tif err != nil {")
		fmt.Fprintln(b, "\t\treturn nil, err")
		fmt.Fprintln(b, "\t}")
		fmt.Fprintf(b, "\treturn &axiom.App{Path: %q, Module: module}, nil\n", filepath.ToSlash(path))
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
	fmt.Fprintf(b, "func New%s(impl %sActivities, opts ...axiom.Option) (*axiom.Engine, error) {\n", domain, domain)
	fmt.Fprintln(b, "\tif impl == nil {")
	fmt.Fprintf(b, "\t\treturn nil, axiom.Error{Code: \"AX500\", Kind: \"config\", Message: %q}\n", domain+" activities implementation is required")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintf(b, "\tapp, err := Load%s()\n", domain)
	fmt.Fprintln(b, "\tif err != nil {")
	fmt.Fprintln(b, "\t\treturn nil, err")
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\tregistry := axiom.ActivityRegistry{")
	for _, activity := range activities {
		name := exportName(activity.Name)
		fmt.Fprintf(b, "\t\tActivity%s: adapt%s(impl.%s),\n", name, name, name)
	}
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "\tall := append([]axiom.Option{axiom.WithActivities(registry)}, opts...)")
	fmt.Fprintln(b, "\treturn app.New(all...)")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeAdapters(b *bytes.Buffer, module *compiler.Module, activities []lang.ActivityDecl) {
	for _, activity := range activities {
		name := exportName(activity.Name)
		fmt.Fprintf(b, "func adapt%s(fn func(context.Context, %sInput) (%sOutput, error)) axiom.Activity {\n", name, name, name)
		fmt.Fprintln(b, "\treturn func(ctx context.Context, input axiom.Input) (axiom.Output, error) {")
		fmt.Fprintf(b, "\t\ttypedInput, err := decode%sInput(input)\n", name)
		fmt.Fprintln(b, "\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\treturn nil, err")
		fmt.Fprintln(b, "\t\t}")
		fmt.Fprintln(b, "\t\tresult, err := fn(ctx, typedInput)")
		fmt.Fprintln(b, "\t\tif err != nil {")
		fmt.Fprintln(b, "\t\t\treturn nil, err")
		fmt.Fprintln(b, "\t\t}")
		fmt.Fprintf(b, "\t\treturn encode%sOutput(result), nil\n", name)
		fmt.Fprintln(b, "\t}")
		fmt.Fprintln(b, "}")
		fmt.Fprintln(b)
		writeInputDecoder(b, module, activity)
		writeOutputEncoder(b, activity)
	}
}

func writeInputDecoder(b *bytes.Buffer, module *compiler.Module, activity lang.ActivityDecl) {
	name := exportName(activity.Name)
	fmt.Fprintf(b, "func decode%sInput(input axiom.Input) (%sInput, error) {\n", name, name)
	fmt.Fprintf(b, "\tvar out %sInput\n", name)
	for _, binding := range activity.Input {
		field := exportName(binding.Name)
		typ := inferBindingType(module, binding)
		fmt.Fprintf(b, "\tif value, ok := input[%q]; ok {\n", binding.Name)
		writeDecodeAssign(b, "out."+field, "value", activity.Name+"."+binding.Name, typ)
		fmt.Fprintln(b, "\t}")
	}
	fmt.Fprintln(b, "\treturn out, nil")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeOutputEncoder(b *bytes.Buffer, activity lang.ActivityDecl) {
	name := exportName(activity.Name)
	fmt.Fprintf(b, "func encode%sOutput(output %sOutput) axiom.Output {\n", name, name)
	fmt.Fprintln(b, "\treturn axiom.Output{")
	for _, field := range activity.Output {
		fmt.Fprintf(b, "\t\t%q: output.%s,\n", field.Name, exportName(field.Name))
	}
	fmt.Fprintln(b, "\t}")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)
}

func writeDecodeAssign(b *bytes.Buffer, target string, source string, entity string, axmType string) {
	nullable := strings.HasSuffix(axmType, "?")
	base := strings.TrimSuffix(axmType, "?")
	if nullable {
		fmt.Fprintf(b, "\t\tif %s == nil {\n", source)
		fmt.Fprintf(b, "\t\t\t%s = nil\n", target)
		fmt.Fprintln(b, "\t\t} else {")
	}
	indent := "\t\t"
	if nullable {
		indent = "\t\t\t"
	}
	assign := func(format string, args ...any) {
		fmt.Fprintf(b, indent+format+"\n", args...)
	}
	switch {
	case base == "String":
		assign("converted, ok := %s.(string)", source)
		assign("if !ok {")
		assign("\treturn out, axiomTypeError(%q, %s, %q)", entity, source, axmType)
		assign("}")
		if nullable {
			assign("%s = &converted", target)
		} else {
			assign("%s = converted", target)
		}
	case base == "Bool":
		assign("converted, ok := %s.(bool)", source)
		assign("if !ok {")
		assign("\treturn out, axiomTypeError(%q, %s, %q)", entity, source, axmType)
		assign("}")
		if nullable {
			assign("%s = &converted", target)
		} else {
			assign("%s = converted", target)
		}
	case base == "Int":
		assign("converted, ok := axiomToInt(%s)", source)
		assign("if !ok {")
		assign("\treturn out, axiomTypeError(%q, %s, %q)", entity, source, axmType)
		assign("}")
		if nullable {
			assign("%s = &converted", target)
		} else {
			assign("%s = converted", target)
		}
	case base == "Float":
		assign("converted, ok := axiomToFloat(%s)", source)
		assign("if !ok {")
		assign("\treturn out, axiomTypeError(%q, %s, %q)", entity, source, axmType)
		assign("}")
		if nullable {
			assign("%s = &converted", target)
		} else {
			assign("%s = converted", target)
		}
	case base == "Object" || strings.HasPrefix(base, "Map<"):
		assign("converted, ok := %s.(map[string]any)", source)
		assign("if !ok {")
		assign("\treturn out, axiomTypeError(%q, %s, %q)", entity, source, axmType)
		assign("}")
		if nullable {
			assign("%s = &converted", target)
		} else {
			assign("%s = converted", target)
		}
	case strings.HasPrefix(base, "List<"):
		elem := strings.TrimSuffix(strings.TrimPrefix(base, "List<"), ">")
		assign("converted, ok := axiomTo%sSlice(%s)", exportName(elem), source)
		assign("if !ok {")
		assign("\treturn out, axiomTypeError(%q, %s, %q)", entity, source, axmType)
		assign("}")
		if nullable {
			assign("%s = &converted", target)
		} else {
			assign("%s = converted", target)
		}
	default:
		if nullable {
			assign("converted := %s", source)
			assign("%s = &converted", target)
		} else {
			assign("%s = %s", target, source)
		}
	}
	if nullable {
		fmt.Fprintln(b, "\t\t}")
	}
}

func writeHelpers(b *bytes.Buffer) {
	b.WriteString(`func axiomTypeError(entity string, value any, want string) error {
	return axiom.Error{Code: "AX503", Kind: "activity", Entity: entity, Message: fmt.Sprintf("type mismatch for %s: got %T, want %s", entity, value, want)}
}

func axiomToInt(value any) (int, bool) {
	switch v := value.(type) {
	case int:
		return v, true
	case int8:
		return int(v), true
	case int16:
		return int(v), true
	case int32:
		return int(v), true
	case int64:
		return int(v), true
	default:
		return 0, false
	}
}

func axiomToFloat(value any) (float64, bool) {
	switch v := value.(type) {
	case float32:
		return float64(v), true
	case float64:
		return v, true
	case int:
		return float64(v), true
	case int8:
		return float64(v), true
	case int16:
		return float64(v), true
	case int32:
		return float64(v), true
	case int64:
		return float64(v), true
	default:
		return 0, false
	}
}

func axiomToStringSlice(value any) ([]string, bool) {
	switch v := value.(type) {
	case []string:
		return v, true
	case []any:
		out := make([]string, len(v))
		for i, item := range v {
			converted, ok := item.(string)
			if !ok {
				return nil, false
			}
			out[i] = converted
		}
		return out, true
	default:
		return nil, false
	}
}

func axiomToBoolSlice(value any) ([]bool, bool) {
	switch v := value.(type) {
	case []bool:
		return v, true
	case []any:
		out := make([]bool, len(v))
		for i, item := range v {
			converted, ok := item.(bool)
			if !ok {
				return nil, false
			}
			out[i] = converted
		}
		return out, true
	default:
		return nil, false
	}
}

func axiomToIntSlice(value any) ([]int, bool) {
	switch v := value.(type) {
	case []int:
		return v, true
	case []any:
		out := make([]int, len(v))
		for i, item := range v {
			converted, ok := axiomToInt(item)
			if !ok {
				return nil, false
			}
			out[i] = converted
		}
		return out, true
	default:
		return nil, false
	}
}

func axiomToFloatSlice(value any) ([]float64, bool) {
	switch v := value.(type) {
	case []float64:
		return v, true
	case []float32:
		out := make([]float64, len(v))
		for i, item := range v {
			out[i] = float64(item)
		}
		return out, true
	case []any:
		out := make([]float64, len(v))
		for i, item := range v {
			converted, ok := axiomToFloat(item)
			if !ok {
				return nil, false
			}
			out[i] = converted
		}
		return out, true
	default:
		return nil, false
	}
}

func axiomToObjectSlice(value any) ([]map[string]any, bool) {
	switch v := value.(type) {
	case []map[string]any:
		return v, true
	case []any:
		out := make([]map[string]any, len(v))
		for i, item := range v {
			converted, ok := item.(map[string]any)
			if !ok {
				return nil, false
			}
			out[i] = converted
		}
		return out, true
	default:
		return nil, false
	}
}

func axiomToAnySlice(value any) ([]any, bool) {
	switch v := value.(type) {
	case []any:
		return v, true
	default:
		return nil, false
	}
}
`)
}

// ── Diff ──────────────────────────────────────────────────────────────────

// ActivityDiff describes how a single activity changed between two versions.
type ActivityDiff struct {
	Name        string
	Kind        string // "added", "removed", "changed"
	OldLine     int
	NewLine     int
	InputDiffs  []FieldDiff
	OutputDiffs []FieldDiff
}

// FieldDiff describes how a single input/output field changed.
type FieldDiff struct {
	Name    string
	Kind    string // "added", "removed", "changed"
	OldType string
	NewType string
}

// DiffResult holds the full difference between two .axm versions.
type DiffResult struct {
	HashChanged bool
	OldHash     string
	NewHash     string
	Activities  []ActivityDiff
}

// Diff compares two compiled modules and returns structural differences.
func Diff(oldSrc, newSrc []byte, oldMod, newMod *compiler.Module) *DiffResult {
	oldHash := fmt.Sprintf("%x", sha256.Sum256(oldSrc))
	newHash := fmt.Sprintf("%x", sha256.Sum256(newSrc))

	result := &DiffResult{
		OldHash: oldHash,
		NewHash: newHash,
	}
	if oldHash != newHash {
		result.HashChanged = true
	}

	oldActs := externalActivities(oldMod)
	newActs := externalActivities(newMod)

	oldByName := make(map[string]lang.ActivityDecl, len(oldActs))
	for _, a := range oldActs {
		oldByName[a.Name] = a
	}
	newByName := make(map[string]lang.ActivityDecl, len(newActs))
	for _, a := range newActs {
		newByName[a.Name] = a
	}

	// Added activities.
	for _, a := range newActs {
		if _, ok := oldByName[a.Name]; !ok {
			ad := ActivityDiff{Name: a.Name, Kind: "added", NewLine: a.Line}
			for _, f := range a.Input {
				ad.InputDiffs = append(ad.InputDiffs, FieldDiff{Name: f.Name, Kind: "added", NewType: inferBindingType(newMod, f)})
			}
			for _, f := range a.Output {
				ad.OutputDiffs = append(ad.OutputDiffs, FieldDiff{Name: f.Name, Kind: "added", NewType: f.Type})
			}
			result.Activities = append(result.Activities, ad)
		}
	}

	// Removed activities.
	for _, a := range oldActs {
		if _, ok := newByName[a.Name]; !ok {
			ad := ActivityDiff{Name: a.Name, Kind: "removed", OldLine: a.Line}
			for _, f := range a.Input {
				ad.InputDiffs = append(ad.InputDiffs, FieldDiff{Name: f.Name, Kind: "removed", OldType: inferBindingType(oldMod, f)})
			}
			for _, f := range a.Output {
				ad.OutputDiffs = append(ad.OutputDiffs, FieldDiff{Name: f.Name, Kind: "removed", OldType: f.Type})
			}
			result.Activities = append(result.Activities, ad)
		}
	}

	// Changed activities.
	for _, a := range newActs {
		oldA, ok := oldByName[a.Name]
		if !ok {
			continue
		}
		ad := ActivityDiff{Name: a.Name, Kind: "changed", OldLine: oldA.Line, NewLine: a.Line}

		oldIn := fieldMap(oldA.Input, oldMod)
		newIn := fieldMap(a.Input, newMod)
		ad.InputDiffs = diffFields(oldIn, newIn)

		oldOut := fieldTypeMap(oldA.Output)
		newOut := fieldTypeMap(a.Output)
		ad.OutputDiffs = diffFields(oldOut, newOut)

		if len(ad.InputDiffs) > 0 || len(ad.OutputDiffs) > 0 {
			result.Activities = append(result.Activities, ad)
		}
	}

	return result
}

func fieldMap(bindings []lang.Binding, mod *compiler.Module) map[string]string {
	m := make(map[string]string, len(bindings))
	for _, b := range bindings {
		m[b.Name] = inferBindingType(mod, b)
	}
	return m
}

func fieldTypeMap(fields []lang.FieldDecl) map[string]string {
	m := make(map[string]string, len(fields))
	for _, f := range fields {
		m[f.Name] = f.Type
	}
	return m
}

func diffFields(old, new map[string]string) []FieldDiff {
	var diffs []FieldDiff
	for name, newType := range new {
		oldType, ok := old[name]
		if !ok {
			diffs = append(diffs, FieldDiff{Name: name, Kind: "added", NewType: newType})
		} else if oldType != newType {
			diffs = append(diffs, FieldDiff{Name: name, Kind: "changed", OldType: oldType, NewType: newType})
		}
	}
	for name, oldType := range old {
		if _, ok := new[name]; !ok {
			diffs = append(diffs, FieldDiff{Name: name, Kind: "removed", OldType: oldType})
		}
	}
	sort.Slice(diffs, func(i, j int) bool { return diffs[i].Name < diffs[j].Name })
	return diffs
}

func externalActivities(module *compiler.Module) []lang.ActivityDecl {
	var activities []lang.ActivityDecl
	for _, activity := range module.Activities {
		if activity.Effect == "none" {
			continue
		}
		activities = append(activities, activity)
	}
	sort.Slice(activities, func(i, j int) bool {
		return activities[i].Name < activities[j].Name
	})
	return activities
}

func inferBindingType(module *compiler.Module, binding lang.Binding) string {
	refs := lang.ExprRefs(binding.Expr)
	if len(refs) != 1 {
		return "Any"
	}
	return inferRefType(module, refs[0])
}

func inferRefType(module *compiler.Module, ref string) string {
	if symbol, ok := module.Symbols[ref]; ok && symbol.Type != "" && symbol.Type != "Any" {
		return symbol.Type
	}
	parts := strings.Split(ref, ".")
	if len(parts) >= 2 {
		if fact, ok := module.Facts[parts[0]]; ok {
			for _, expose := range fact.Expose {
				if expose.Name == parts[1] {
					return inferBindingType(module, expose)
				}
			}
		}
		if symbol, ok := module.Symbols[parts[0]+"."+parts[1]]; ok && symbol.Type != "" {
			return symbol.Type
		}
	}
	return "Any"
}

func goType(typeName string) string {
	nullable := strings.HasSuffix(typeName, "?")
	base := strings.TrimSuffix(typeName, "?")
	typ := goBaseType(base)
	if nullable {
		return "*" + typ
	}
	return typ
}

func goBaseType(typeName string) string {
	switch typeName {
	case "String", "Time", "Duration":
		return "string"
	case "Bool":
		return "bool"
	case "Int":
		return "int"
	case "Float":
		return "float64"
	case "Object":
		return "map[string]any"
	case "Any":
		return "any"
	default:
		if strings.HasPrefix(typeName, "List<") && strings.HasSuffix(typeName, ">") {
			return "[]" + goType(strings.TrimSuffix(strings.TrimPrefix(typeName, "List<"), ">"))
		}
		if strings.HasPrefix(typeName, "Map<") {
			return "map[string]any"
		}
		return "any"
	}
}

func exportName(name string) string {
	parts := splitName(name)
	for i, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[i] = string(runes)
	}
	return strings.Join(parts, "")
}

func lowerSnake(name string) string {
	parts := splitName(name)
	for i, part := range parts {
		parts[i] = strings.ToLower(part)
	}
	return strings.Join(parts, "_")
}

func splitName(name string) []string {
	var parts []string
	var current []rune
	flush := func() {
		if len(current) > 0 {
			parts = append(parts, string(current))
			current = nil
		}
	}
	var prevLower bool
	for _, r := range name {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			flush()
			prevLower = false
			continue
		}
		if unicode.IsUpper(r) && prevLower {
			flush()
		}
		current = append(current, r)
		prevLower = unicode.IsLower(r) || unicode.IsDigit(r)
	}
	flush()
	return parts
}
