package codegen

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Homiakus/axiom/internal/compiler"
)

func TestGenerateWelcomeWrapper(t *testing.T) {
	source := readExample(t, "welcome.axm")
	module, err := compiler.Compile(source)
	if err != nil {
		t.Fatalf("Compile() error = %v", err)
	}
	files, err := Generate(module, Options{PackageName: "generated", SourcePath: "welcome.axm", Source: source})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if len(files) != 2 {
		t.Fatalf("files = %d, want 2", len(files))
	}
	gen := string(files[0].Content)
	for _, want := range []string{
		"// Code generated by axiomgen",
		"const WelcomeAXMSource",
		"const WelcomeAXMHash",
		"ActivitySendWelcomeEmail = \"SendWelcomeEmail\"",
		"type WelcomeActivities interface",
		"UserId *string `json:\"userId\"`",
		"Email  *string `json:\"email\"`",
		"Sent bool `json:\"sent\"`",
		"func NewWelcome(impl WelcomeActivities",
	} {
		if !strings.Contains(gen, want) {
			t.Fatalf("generated file missing %q:\n%s", want, gen)
		}
	}
	if !files[1].Once {
		t.Fatalf("stubs file should be create-once")
	}
	if !strings.Contains(string(files[1].Content), "type WelcomeActivityImpl struct{}") {
		t.Fatalf("stubs file missing implementation skeleton:\n%s", files[1].Content)
	}
}

func TestGeneratedWelcomeWrapperParsesOffline(t *testing.T) {
	source := readExample(t, "welcome.axm")
	module, err := compiler.Compile(source)
	if err != nil {
		t.Fatalf("Compile() error = %v", err)
	}
	files, err := Generate(module, Options{PackageName: "generated", SourcePath: "welcome.axm", Source: source})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	fset := token.NewFileSet()
	for _, file := range files {
		if _, err := parser.ParseFile(fset, file.Name, file.Content, parser.AllErrors); err != nil {
			t.Fatalf("generated %s is not valid Go syntax: %v", file.Name, err)
		}
	}
}

func TestGenerateTransfersSourceComments(t *testing.T) {
	source := []byte(`# module comment
domain Welcome # inline domain comment

signal UserRegistered:
  userId: String
  email: String

context User:
  id: String?
  email: String?
  welcomeSent: Bool = false

computed userReady: Bool =
  User.id exists and User.email exists

fact RegisteredUser when:
  userReady
expose:
  id = User.id
  email = User.email

policy emailPolicy:
  retry: 2
  timeout: 5s
  concurrency: once
  idempotency: required

# sends welcome message
activity SendWelcomeEmail:
  input:
    userId = RegisteredUser.id # user id comment
    email = RegisteredUser.email
  output:
    sent: Bool
  effect: external
  idempotencyKey: RegisteredUser.id
  policy: emailPolicy

rule captureRegistration:
  on UserRegistered
  write:
    User.id = signal.userId
    User.email = signal.email

rule sendWelcomeEmail:
  on changed(User.email)
  require:
    RegisteredUser
  run: SendWelcomeEmail
  write:
    User.welcomeSent = output.sent

claim welcomeSentRequiresEmail:
  always:
    User.welcomeSent == true implies User.email exists
`)
	module, err := compiler.Compile(source)
	if err != nil {
		t.Fatalf("Compile() error = %v", err)
	}
	files, err := Generate(module, Options{PackageName: "generated", SourcePath: "welcome.axm", Source: source})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	gen := string(files[0].Content)
	if strings.Contains(gen, "Axiom source comments") {
		t.Fatalf("generated file should not aggregate comments at the top:\n%s", gen)
	}
	for _, want := range []string{
		"// sends welcome message\n\tActivitySendWelcomeEmail = \"SendWelcomeEmail\"",
		"// sends welcome message\ntype SendWelcomeEmailInput struct",
		"// user id comment\n\tUserId *string `json:\"userId\"`",
		"// sends welcome message\n\tSendWelcomeEmail(ctx context.Context, input SendWelcomeEmailInput) (SendWelcomeEmailOutput, error)",
	} {
		if !strings.Contains(gen, want) {
			t.Fatalf("generated file missing contextual comment %q:\n%s", want, gen)
		}
	}
}

func readExample(t *testing.T, name string) []byte {
	t.Helper()
	source, err := os.ReadFile(filepath.Join(repoRoot(t), "examples", "axiom-files", name))
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	return source
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", "..", "..", ".."))
	if err != nil {
		t.Fatalf("Abs() error = %v", err)
	}
	return root
}
