package codegen

import (
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/Homiakus/axiom/internal/compiler"
)

func TestGenerateWelcomeWrapper(t *testing.T) {
	source := readExample(t, "welcome.axm")
	module, err := compiler.Compile(source)
	if err != nil {
		t.Fatalf("Compile() error = %v", err)
	}
	files, err := Generate(module, Options{PackageName: "generated", SourcePath: "welcome.axm", Source: source})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if len(files) != 2 {
		t.Fatalf("files = %d, want 2", len(files))
	}
	gen := string(files[0].Content)
	for _, want := range []string{
		"// Code generated by axiomgen",
		"const WelcomeAXMSource",
		"const WelcomeAXMHash",
		"ActivitySendWelcomeEmail = \"SendWelcomeEmail\"",
		"type WelcomeActivities interface",
		"UserId *string `json:\"userId\"`",
		"Email  *string `json:\"email\"`",
		"Sent bool `json:\"sent\"`",
		"func NewWelcome(impl WelcomeActivities",
	} {
		if !strings.Contains(gen, want) {
			t.Fatalf("generated file missing %q:\n%s", want, gen)
		}
	}
	if !files[1].Once {
		t.Fatalf("stubs file should be create-once")
	}
	if !strings.Contains(string(files[1].Content), "type WelcomeActivityImpl struct{}") {
		t.Fatalf("stubs file missing implementation skeleton:\n%s", files[1].Content)
	}
}

func TestGeneratedWelcomeWrapperRuns(t *testing.T) {
	source := readExample(t, "welcome.axm")
	module, err := compiler.Compile(source)
	if err != nil {
		t.Fatalf("Compile() error = %v", err)
	}
	files, err := Generate(module, Options{PackageName: "generated", SourcePath: "welcome.axm", Source: source})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	dir := t.TempDir()
	repo := repoRoot(t)
	writeFile(t, dir, "go.mod", []byte("module generatedtest\n\ngo 1.26\n\nrequire axiom v0.0.0\n\nreplace axiom => "+strconv.Quote(filepath.ToSlash(repo))+"\n"))
	for _, file := range files {
		writeFile(t, dir, file.Name, file.Content)
	}
	writeFile(t, dir, "welcome_runtime_test.go", []byte(`package generated

import (
	"context"
	"testing"

	"github.com/Homiakus/axiom"
)

type impl struct{}

func (impl) SendWelcomeEmail(ctx context.Context, input SendWelcomeEmailInput) (SendWelcomeEmailOutput, error) {
	if input.UserId == nil || *input.UserId != "u1" || input.Email == nil || *input.Email != "user@example.com" {
		return SendWelcomeEmailOutput{}, axiom.Error{Code: "TEST", Message: "bad input"}
	}
	return SendWelcomeEmailOutput{Sent: true}, nil
}

func TestGeneratedRuntime(t *testing.T) {
	ctx := context.Background()
	engine, err := NewWelcome(impl{})
	if err != nil {
		t.Fatalf("NewWelcome() error = %v", err)
	}
	if err := engine.Start(ctx, "gen-1", nil); err != nil {
		t.Fatalf("Start() error = %v", err)
	}
	if err := engine.Signal(ctx, "gen-1", "UserRegistered", axiom.Input{"userId": "u1", "email": "user@example.com"}); err != nil {
		t.Fatalf("Signal() error = %v", err)
	}
	if err := engine.RunUntilIdle(ctx, "gen-1"); err != nil {
		t.Fatalf("RunUntilIdle() error = %v", err)
	}
}
`))
	for _, args := range [][]string{{"mod", "tidy"}, {"test", "."}} {
		cmd := exec.Command("go", args...)
		cmd.Dir = dir
		output, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("go %s generated package error = %v\n%s", strings.Join(args, " "), err, output)
		}
	}
}

func TestGenerateTransfersSourceComments(t *testing.T) {
	source := []byte(`# module comment
domain Welcome # inline domain comment

signal UserRegistered:
  userId: String
  email: String

context User:
  id: String?
  email: String?
  welcomeSent: Bool = false

computed userReady: Bool =
  User.id exists and User.email exists

fact RegisteredUser when:
  userReady
expose:
  id = User.id
  email = User.email

policy emailPolicy:
  retry: 2
  timeout: 5s
  concurrency: once
  idempotency: required

# sends welcome message
activity SendWelcomeEmail:
  input:
    userId = RegisteredUser.id # user id comment
    email = RegisteredUser.email
  output:
    sent: Bool
  effect: external
  idempotencyKey: RegisteredUser.id
  policy: emailPolicy

rule captureRegistration:
  on UserRegistered
  write:
    User.id = signal.userId
    User.email = signal.email

rule sendWelcomeEmail:
  on changed(User.email)
  require:
    RegisteredUser
  run: SendWelcomeEmail
  write:
    User.welcomeSent = output.sent

claim welcomeSentRequiresEmail:
  always:
    User.welcomeSent == true implies User.email exists
`)
	module, err := compiler.Compile(source)
	if err != nil {
		t.Fatalf("Compile() error = %v", err)
	}
	files, err := Generate(module, Options{PackageName: "generated", SourcePath: "welcome.axm", Source: source})
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	gen := string(files[0].Content)
	if strings.Contains(gen, "Axiom source comments") {
		t.Fatalf("generated file should not aggregate comments at the top:\n%s", gen)
	}
	for _, want := range []string{
		"// sends welcome message\n\tActivitySendWelcomeEmail = \"SendWelcomeEmail\"",
		"// sends welcome message\ntype SendWelcomeEmailInput struct",
		"// user id comment\n\tUserId *string `json:\"userId\"`",
		"// sends welcome message\n\tSendWelcomeEmail(ctx context.Context, input SendWelcomeEmailInput) (SendWelcomeEmailOutput, error)",
	} {
		if !strings.Contains(gen, want) {
			t.Fatalf("generated file missing contextual comment %q:\n%s", want, gen)
		}
	}
}

func readExample(t *testing.T, name string) []byte {
	t.Helper()
	source, err := os.ReadFile(filepath.Join(repoRoot(t), "examples", "axiom-files", name))
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	return source
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", "..", "..", ".."))
	if err != nil {
		t.Fatalf("Abs() error = %v", err)
	}
	return root
}

func writeFile(t *testing.T, dir string, name string, content []byte) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), content, 0o600); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", name, err)
	}
}
